name: Build and Test
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: action/checkout@v2
      - name: Install node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Install dependences
        run: npm install
      - name: Run units tests
        run: npm test
